[#7] 이메일 인증 기능
HotteokGroup/PPOTTO_BFF pull request #8
Opened 2023-11-09 06:16 UTC by Daphne-dev

<img width="783" alt="스크린샷 2023-11-09 오후 3 13 06" src="https://github.com/HotteokGroup/PPOTTO_BFF/assets/59605994/e0dc9f0d-0af8-4837-b152-817555175e29">

- 이메일 인증 요청
- 이메일 인증 검증 기능
    - 검증 성공 시 회원가입 용 임시 JWT 발급
- BFF 및 내부 MSA 서비스 요청에 대한 에러 처리 추가

2023-11-09 07:06 UTC, argon1025 requested changes
확인부탁드려요~

2023-11-09 07:06 UTC, argon1025 commented on src/auth/dto/send-verification.dto.ts
> +  verificationType: SendVerificationRequestVerificationTypeEnum;
enum 명칭이 너무 기네요..
openAPI에서도 방법은 찾아보겠지만
user-api-client 내에 user-api-client.enum.ts 파일을 두고
한번 맵핑해서 제공하는것이 어떨까요?

이대로면 내부 서비스에서 용어가 변경될 경우 BFF의 모든 코드도 대응해야해요.

2023-11-09 07:06 UTC, argon1025 commented on src/auth/auth.controller.ts
> +    return plainToInstance(SendVerificationResponse, this.authService.sendVerification(data));
두번째 인자 프로미스형태로 줘도 되나요?

2023-11-09 07:06 UTC, argon1025 commented on src/internal/user/user-api-client.service.ts
> +      const errorInfo = ERROR_CODE[errorCode];
이러면 User가 업데이트 후 BFF가 대응이 늦어졌을 경우 errorInfo를 찾을 수 없어
문제가 있어 보입니다.

User / BFF간 의존성을 분리 부탁드려요

2023-11-09 07:06 UTC, argon1025 requested changes
확인부탁드려요~

2023-11-09 13:42 UTC, Daphne-dev commented on src/auth/auth.service.ts
> +    const { id } = await this.userApi.sendVerification(params);
@argon1025 
BFF 수준에서 에러코드 별로 공개할 에러로 구분해서 `UserApiException` 리턴
`AllExceptionsFilter`에서 내부 서비스 exception 값 내부 로깅

위와 같이 처리하도록 했습니다. 
따라서 에러코드 별로 BFF 에러로 리턴을 하도록 되어있습니다.

제 의도는 모든 내부 서비스에서 발생하는 에러들을
`AllExceptionsFilter`에서 일괄적으로 처리하고 싶었습니다. 

 User 서비스에서 발생한 에러를
`UserApiClientService`에서 핸들링하여 BFF에서 대응되는 에러코드로 변경 후
`UserApiException`으로 만들어 `AllExceptionsFilter`에서 모두 처리합니다.

추가적으로 이 부분이 고민됩니다.
1. 내부 서비스의 에러는 BFF 서비스로 전파해서 BFF 서비스에서 처리하게 할 것인지..
2. 아니면 위의 방식대로 일괄적으로 처리할지..

2023-11-10 12:44 UTC, argon1025 requested changes
확인해주세요!

2023-11-10 12:44 UTC, argon1025 commented on src/auth/dto/send-verification.dto.ts
> +  @ApiProperty({ description: '인증 타입', example: VerificationType.Email })
OpenAPI SDK 생성 시 enum은 ApiProperty에 enum 파라미터가 필수입니다 추가 부탁드려요

2023-11-10 12:44 UTC, argon1025 commented on src/internal/user/user-client.enum.ts
> +export const VerificationType = SendVerificationRequestVerificationTypeEnum;
SendVerificationRequestVerificationTypeEnum 가 타입이 아닌가요?
```
export type VerificationType = SendVerificationRequestVerificationTypeEnum;
```

2023-11-10 12:44 UTC, argon1025 commented on src/internal/user/user-client.exception.ts
> +  constructor(errorObject: ErrorObject<string>, error: AxiosError) {
errorObject, error 명칭이 조금 모호한 것 같습니다.
errorObject의 경우 response의 body Data,
error의 경우 로직 상 발생가능한 모든 에러라면
뭔가 이해하기 쉬운 명칭으로 변경하면 어떨까요?
이후 작업 시 getErrorInfo와 getError의 차이를 알 수 없을 것같아요

그리고 error가 무조건 AxiosError만일까요?
userClient에서 로직상 에러가 발생하면 다른 에러도 발생할 수 있기 때문에 Error로 일괄 받아서 넣는 게 좋을 것 같습니다!

2023-11-10 12:44 UTC, argon1025 commented on src/internal/user/user-client.service.ts
> +    return new InternalServerErrorException(ERROR_CODE.INTERNAL_SERVER_ERROR);
위, 아래 ERROR_CODE 의존성 분리 부탁드려요

2023-11-10 12:49 UTC, Daphne-dev commented on src/internal/user/user-client.enum.ts
> +export const VerificationType = SendVerificationRequestVerificationTypeEnum;
@argon1025 
타입이면서 변수입니다~

2023-11-10 13:00 UTC, argon1025 approved these changes
좋습니다~

2023-11-10 13:03 UTC, argon1025 approved these changes
굳~

2023-11-10 13:03 UTC, merged